# Generated by Django 3.1 on 2021-06-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
